// backend/src/lib/productionConfig.js
// ─────────────────────────────────────────────────────────────
// INSTALL-02 — Automated Secret & Production Config Generation.
//
// Ensures the production config file (lib/config.js's resolveProductionConfigPath() —
// STUDIX_CONFIG_PATH override, else %ProgramData%\Studix\config\.env) exists with a
// cryptographically random SESSION_SECRET, so a packaged install never requires an operator
// to hand-generate a secret or edit .env. Reuses lib/config.js's existing path precedence as
// the sole source of truth — this module does not invent a second config system, it only
// ever WRITES the file lib/config.js already knows how to READ.
//
// Idempotency is the core safety property: if the file already exists with a non-empty
// SESSION_SECRET, it is returned unmodified — not read-then-rewritten, not touched at the
// filesystem level at all. That's what guarantees repeated runs (fresh install, every
// subsequent upgrade re-run) never rotate the secret and never invalidate existing sessions.
//
// If the file exists but SESSION_SECRET is missing/empty (e.g. manually edited, or a file
// from an unrelated source), this fails closed with ProductionConfigError rather than
// guessing at a repair — there is no existing "repair a config file" pattern anywhere else in
// this codebase to extend, and silently patching or rewriting a file an operator already has
// in place is exactly the kind of destructive-recovery behavior this phase must not invent.
//
// DATABASE_URL: INSTALL-02 does not install or configure PostgreSQL (INSTALL-03) and never
// invents credentials. If a caller passes `databaseUrl` explicitly (the future installer's own
// orchestration, or an operator's own environment), it's written verbatim; otherwise the
// generated file simply omits DATABASE_URL, which is fully compatible with the existing
// fail-closed startup check (lib/startupErrors.js validateDatabaseUrl) — that check already
// produces a clear operator-facing message the next time the server actually starts. Nothing
// about that validation is weakened or bypassed here.
//
// File permissions: the meaningful ACL restriction on %ProgramData%\Studix\config\ (so only
// SYSTEM/Administrators/the service account can read it) is a Windows-installer-time concern
// (icacls, run elevated during setup) — Node's fs.writeFileSync `mode` option does not control
// NTFS ACLs on Windows at all, so setting one here would be a false sense of security, not a
// real control. Deliberately left to the future Inno Setup installer rather than implemented
// (or faked) here.
// ─────────────────────────────────────────────────────────────
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import dotenv from 'dotenv';
import { resolveProductionConfigPath } from './config.js';

export { resolveProductionConfigPath };

export class ProductionConfigError extends Error {}

const SESSION_SECRET_BYTES = 32; // 256 bits — comfortably above any HMAC/session-signing minimum

// generateSessionSecret: crypto.randomBytes (CSPRNG) only — never Math.random(). `randomBytes`
// is injectable purely so a test can assert this actually calls a CSPRNG-shaped function
// rather than trusting the import alone.
export function generateSessionSecret(randomBytes = crypto.randomBytes) {
  return randomBytes(SESSION_SECRET_BYTES).toString('hex');
}

function readExistingSessionSecret(configPath, readFileSync) {
  const raw = readFileSync(configPath, 'utf8');
  const parsed = dotenv.parse(raw);
  const secret = parsed.SESSION_SECRET;
  return secret && secret.trim() ? secret : null;
}

// ensureProductionConfig: see file header for the full idempotency/DATABASE_URL/ACL contract.
// Every fs dependency is injectable so tests never touch the real C:\ProgramData.
export function ensureProductionConfig({
  configPath = resolveProductionConfigPath(),
  databaseUrl,
  existsSync = fs.existsSync,
  readFileSync = fs.readFileSync,
  writeFileSync = fs.writeFileSync,
  mkdirSync = fs.mkdirSync,
  randomBytes = crypto.randomBytes,
} = {}) {
  if (existsSync(configPath)) {
    const existingSecret = readExistingSessionSecret(configPath, readFileSync);
    if (existingSecret) {
      return { created: false, path: configPath };
    }
    throw new ProductionConfigError(
      `Production config already exists at ${configPath} but has no SESSION_SECRET. Refusing ` +
      'to modify it automatically. Add a SESSION_SECRET line manually, or remove the file to ' +
      'let it be regenerated from scratch.'
    );
  }

  mkdirSync(path.dirname(configPath), { recursive: true });

  const secret = generateSessionSecret(randomBytes);
  const lines = [
    '# Generated by Studix (INSTALL-02 production config generator).',
    '# Lives outside the application/release directory — never committed, never shipped in',
    '# release/win-x64/studix. SESSION_SECRET below is generated once and preserved across',
    '# every subsequent run/upgrade — it is never rotated automatically.',
    '#',
    '# STUDIX_BACKUP_DIR / STUDIX_LOG_DIR already default to %ProgramData%\\Studix\\backups and',
    '# %ProgramData%\\Studix\\logs (backend/src/db/backup.js, backend/src/lib/logger.js) — only',
    '# set them here to override those defaults.',
    '',
    `SESSION_SECRET=${secret}`,
    ...(databaseUrl ? [`DATABASE_URL=${databaseUrl}`] : []),
    '',
  ];

  writeFileSync(configPath, lines.join('\n'), 'utf8');

  return { created: true, path: configPath };
}
