// backend/src/lib/provisioningAdminConfig.js
// ─────────────────────────────────────────────────────────────
// INSTALL-10 — persists the studix_admin (provisioning/migration) connection string in a file
// SEPARATE from the runtime production config (lib/config.js's resolveProductionConfigPath()/
// .env) that server.js loads. Deliberately never wired into lib/config.js's loadEnvConfig() or
// any process.env-mutating path — this module is read ONLY by
// backend/src/installer/firstInstall.js's short-lived orchestrator, never by the long-running
// StudixApp service. That separation is the entire point: the running application must never
// hold or expose the admin credential (OD3, migration/reports/INSTALL-10_..._REPORT.md).
//
// Same %ProgramData%\Studix\config\ directory as the runtime .env — the ACL restricting that
// whole directory to Administrators/SYSTEM (installer/studix.iss [Dirs], admins-full
// system-full) already covers this file too via NTFS inheritance; no installer change needed.
// A DIFFERENT FILENAME within that same directory is what keeps it out of loadEnvConfig()'s
// reach — loadEnvConfig() only ever reads resolveProductionConfigPath()'s own exact path.
//
// Idempotency mirrors lib/productionConfig.js's ensureProductionConfig exactly: written once,
// on first-ever provisioning, never rewritten afterward — provisionPostgres()/ensureAppRole()
// never rotate an already-created role's password, so there is never a reason to overwrite this
// file once it exists.
//
// Uses dotenv.parse (a pure string->object parser with NO process.env side effect) to read the
// value back — never dotenv.config(), which mutates process.env and is exactly the mechanism
// this module must never trigger for this file.
// ─────────────────────────────────────────────────────────────
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';

export class ProvisioningAdminConfigError extends Error {}

const ADMIN_URL_KEY = 'STUDIX_DB_ADMIN_URL'; // same name as bootstrapDatabase.js's existing override contract

export function resolveProvisioningAdminConfigPath() {
  if (process.env.STUDIX_ADMIN_CONFIG_PATH) return process.env.STUDIX_ADMIN_CONFIG_PATH;
  const programData = process.env.ProgramData || 'C:\\ProgramData';
  return path.join(programData, 'Studix', 'config', 'admin.env');
}

// ensureProvisioningAdminConfig: writes the admin connection string exactly once. If the file
// already exists with a non-empty STUDIX_DB_ADMIN_URL, it is returned unmodified — not
// read-then-rewritten, not touched at the filesystem level at all (identical contract to
// ensureProductionConfig's own SESSION_SECRET handling).
export function ensureProvisioningAdminConfig({
  configPath = resolveProvisioningAdminConfigPath(),
  databaseUrl,
  existsSync = fs.existsSync,
  readFileSync = fs.readFileSync,
  writeFileSync = fs.writeFileSync,
  mkdirSync = fs.mkdirSync,
} = {}) {
  if (existsSync(configPath)) {
    const existing = readProvisioningAdminUrl({ configPath, existsSync, readFileSync });
    if (existing) {
      return { created: false, path: configPath };
    }
    throw new ProvisioningAdminConfigError(
      `ملف بيانات الاعتماد الإداري موجود بالفعل عند ${configPath} لكن بلا ${ADMIN_URL_KEY}. ` +
      'رُفض تعديله تلقائياً — تحقّق منه يدوياً أو احذفه ليُعاد إنشاؤه من الصفر.'
    );
  }
  if (!databaseUrl) {
    throw new ProvisioningAdminConfigError('databaseUrl مطلوب لإنشاء ملف بيانات الاعتماد الإداري لأول مرة.');
  }

  mkdirSync(path.dirname(configPath), { recursive: true });

  const lines = [
    '# Generated by Studix (INSTALL-10 provisioning admin config).',
    '# Provisioning/migration credential ONLY — read exclusively by',
    '# backend/src/installer/firstInstall.js. NEVER loaded by the running application',
    '# (lib/config.js/server.js never read this file) and NEVER rotated automatically.',
    '',
    `${ADMIN_URL_KEY}=${databaseUrl}`,
    '',
  ];
  writeFileSync(configPath, lines.join('\n'), 'utf8');

  return { created: true, path: configPath };
}

// readProvisioningAdminUrl: returns the plain string value, or null if the file/value is
// missing — deliberately does NOT touch process.env (unlike lib/config.js's loadEnvConfig),
// so there is no path by which this value can end up in the running application's environment.
export function readProvisioningAdminUrl({
  configPath = resolveProvisioningAdminConfigPath(),
  existsSync = fs.existsSync,
  readFileSync = fs.readFileSync,
} = {}) {
  if (!existsSync(configPath)) return null;
  const raw = readFileSync(configPath, 'utf8');
  const parsed = dotenv.parse(raw);
  const url = parsed[ADMIN_URL_KEY];
  return url && url.trim() ? url : null;
}
